### ISSUE TITLE
1.Sem/MA1.pdf outdated

### ISSUE THREAD

**Issue by trogper** [citruslee/Studijne-materialy-FIIT#26]
Bola vydaná nová verzia súboru Pred_MA1_1.pdf, pridané nejaké definície a neviem
[matika.elf.stuba.sk/KMAT/...../Pred_MA1_1.pdf](http://matika.elf.stuba.sk/KMAT/MatematickaAnalyza1?action=AttachFile&do=get&target=Pred_MA1_1.pdf)

**Comment by citruslee** [comment]
@trogper please, create a new pull request if you see it fit, until then I am closing this issue, thanks for noticing.
