### ISSUE TITLE
Vytvorenie pull requestu

### ISSUE THREAD

**Issue by Fiitkar** [citruslee/Studijne-materialy-FIIT#51]
Klasika, forkol som si repozitar, pridal som tam priecinok inzinierske_predmety, commitol, pushol a chcel som vytvorit pull request. GitHub interface rozpoznal pridany commit, avsak po kliknuti tlacidla "Create pull request" sa nic nestalo, ziadna odozva. Stale mi pise, ze Checking for mergeability, uz 20 minut bez zmeny pritom pridavam novy adresar so subormi, cize ziaden merge conflict by nemal nastat a aj tak, toto by nemalo zabranit vytvoreniu pull requestu.

**Comment by Fiitkar** [comment]
Ani compare across forks tlacidlo nereaguje

**Comment by Fiitkar** [comment]
Problem bol vo Firefox prehliadaci, druhy browser vyriesil problem

**Comment by citruslee** [comment]
sorry bol som mimo PC, tak vyriesilo sa to teda?
